/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
static yyconst short int yy_accept[172] =
    {   0,
       65,   65,   75,   73,    1,    2,   52,   71,   35,   47,
       69,   53,   54,   33,   31,   59,   32,   65,   34,   19,
       60,   38,   44,   40,   61,   57,   58,   49,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   55,   48,
       56,    1,   43,   71,   62,   71,   45,   69,   69,   68,
       69,   36,   37,   65,   20,   72,   63,   65,   19,   67,
       66,   50,   39,   42,   41,   51,   61,   61,   61,   61,
       61,   61,    7,   61,   61,   61,    3,   61,   61,   61,
       61,   61,   46,   62,   21,   69,   70,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   65,   66,

       72,   72,   72,   63,   63,   66,   66,   20,   66,   66,
       61,   61,   61,   61,   61,   61,   61,   61,    5,    9,
       61,   61,   61,   61,   69,   22,   30,   22,   25,   28,
       26,   23,   27,   24,   29,   66,   66,   20,   66,   64,
       63,   66,   61,   16,   10,   61,   61,   61,    4,   61,
       61,   61,   13,   61,    8,   61,   61,   61,   11,   61,
       61,    6,   61,   61,   12,   14,   15,   61,   17,   18,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    4,
        3,    3,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,    1,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   26,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   25,   38,   39,   25,   40,   41,   25,   42,
       43,   25,   25,   44,   45,   46,   47,   48,   49,   25,
       25,   25,   50,   51,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[53] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    4,    4,
        1,    1,    1,    1,    4,    4,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    1
    } ;

static yyconst short int yy_base[180] =
    {   0,
        0,    0,  339,  340,   50,  340,  315,   47,  340,  328,
       54,  340,  340,  340,  322,  340,  319,   41,   49,   46,
      340,   46,  311,   47,    0,  340,  340,  340,  289,   41,
       38,  291,   35,   43,  295,  281,  286,  290,  340,  276,
      340,   83,  340,   70,  340,   83,  340,   73,   79,  340,
      105,  340,  340,   74,   80,   90,  298,   85,   97,  308,
      153,  340,  340,  340,  340,  340,    0,  288,  278,  290,
      279,  283,  272,  273,  274,  272,    0,  269,  268,  274,
      273,  272,  340,   85,  340,   99,  340,  100,  108,  111,
      112,  115,  116,  120,  122,  124,  196,  197,  191,  210,

      128,  196,  200,  282,   91,  196,  203,    0,  201,  208,
      277,  272,  263,  260,  267,  258,  249,  249,    0,    0,
      230,  230,  240,  233,  250,  340,  340,  251,  340,  340,
      340,  340,  340,  340,  340,  218,  257,  256,  246,  340,
      243,  212,  230,    0,    0,  230,  221,  226,    0,  218,
      219,  206,    0,  203,    0,  191,  116,  109,    0,   93,
       93,    0,   82,   74,    0,    0,    0,   60,    0,    0,
      340,  279,  283,  285,   55,  289,  293,  297,  301
    } ;

static yyconst short int yy_def[180] =
    {   0,
      171,    1,  171,  171,  171,  171,  171,  172,  171,  171,
      173,  171,  171,  171,  171,  171,  171,  171,  171,  174,
      171,  171,  171,  171,  175,  171,  171,  171,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  171,  171,
      171,  171,  171,  172,  171,  172,  171,  176,  176,  171,
      176,  171,  171,  171,  171,  177,  178,  171,  174,  174,
      171,  171,  171,  171,  171,  171,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  171,  172,  171,  176,  171,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  171,   61,

      177,  179,  177,  178,  178,  100,  100,   61,   61,   61,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  176,  171,  171,  176,  171,  171,
      171,  171,  171,  171,  171,  100,  100,  100,  100,  171,
      178,   61,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
        0,  171,  171,  171,  171,  171,  171,  171,  171
    } ;

static yyconst short int yy_nxt[393] =
    {   0,
        4,    4,    5,    6,    5,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       21,   22,   23,   24,   25,   25,   26,    4,   27,   28,
       25,   25,   29,   30,   31,   32,   33,   25,   34,   25,
       25,   25,   25,   35,   36,   25,   25,   37,   38,   39,
       40,   41,   42,   45,   42,   49,   49,   54,   67,   55,
       55,   56,   58,   50,   59,   59,   57,   62,   63,   65,
       66,   61,   69,   72,   46,   75,   45,   76,   70,   77,
       73,   51,   85,   71,   78,   42,   44,   42,   87,   84,
       54,   45,   99,   99,  141,  170,   54,   46,   55,   55,

       86,   54,  102,   55,   55,  100,   86,  103,  125,  126,
       46,   88,   46,   58,   89,   59,   59,  126,  105,  169,
      127,  128,   61,   90,  129,  130,   86,   86,  168,  131,
      167,  132,   91,  133,  166,   86,   92,   93,   86,   86,
      102,   94,   86,   86,  165,  103,   95,   86,   96,   86,
       97,   86,   98,  106,  106,  106,  164,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  107,  106,
      106,  108,  108,  106,  106,  106,  106,  109,  110,  106,
      106,  106,  106,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,

      109,  109,  106,  106,  106,  134,  135,   54,  102,   99,
       99,  107,  102,  140,  107,  107,  136,  103,  107,  142,
      142,  107,  107,   86,   86,  137,  142,  142,  138,  138,
      142,  142,  163,  107,  106,  139,  107,  107,  162,  161,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,   87,
       87,  107,  160,  159,  107,  107,  158,  157,  156,  155,
      105,  107,  107,  154,  153,  152,  151,   86,   86,   44,
      150,   44,   44,   48,  149,   48,   48,   60,   60,   49,
      148,   49,   49,  101,  101,  101,  101,  104,  147,  104,

      104,  103,  103,  103,  103,  146,  145,  144,  143,  105,
      124,  123,  122,  121,  120,  119,  118,  117,  116,  115,
      114,  113,  112,  111,  171,  105,   83,   82,   81,   80,
       79,   74,   68,   64,   53,   52,   47,   43,  171,    3,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171

    } ;

static yyconst short int yy_chk[393] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    8,    5,   11,   11,   18,  175,   18,
       18,   19,   20,   11,   20,   20,   19,   22,   22,   24,
       24,   20,   30,   31,    8,   33,   44,   33,   30,   34,
       31,   11,   48,   30,   34,   42,   46,   42,   49,   46,
       54,   84,   54,   54,  105,  168,   55,   44,   55,   55,

       48,   58,   56,   58,   58,   55,   49,   56,   86,   88,
       46,   51,   84,   59,   51,   59,   59,   89,  105,  164,
       90,   91,   59,   51,   92,   93,   86,   88,  163,   94,
      161,   95,   51,   96,  160,   89,   51,   51,   90,   91,
      101,   51,   92,   93,  158,  101,   51,   94,   51,   95,
       51,   96,   51,   61,   61,   61,  157,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   97,   98,   99,  102,   99,
       99,  106,  103,  102,  106,  106,   99,  103,  107,  109,
      109,  107,  107,   97,   98,  100,  110,  110,  100,  100,
      142,  142,  156,  136,  100,  100,  136,  136,  154,  152,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  125,
      128,  139,  151,  150,  139,  139,  148,  147,  146,  143,
      141,  138,  137,  124,  123,  122,  121,  125,  128,  172,
      118,  172,  172,  173,  117,  173,  173,  174,  174,  176,
      116,  176,  176,  177,  177,  177,  177,  178,  115,  178,

      178,  179,  179,  179,  179,  114,  113,  112,  111,  104,
       82,   81,   80,   79,   78,   76,   75,   74,   73,   72,
       71,   70,   69,   68,   60,   57,   40,   38,   37,   36,
       35,   32,   29,   23,   17,   15,   10,    7,    3,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scannerwork.l"
#define INITIAL 0
#line 4 "scannerwork.l"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include "symbol_table.h"

using namespace std;

int bucketSize = 50;

int line_count=1;
int error_count = 0;

FILE *logout;
FILE *tokenout;

SymbolTable table(bucketSize);

char * strmem;

char* toUppercase(char* input) {
	delete strmem;  ///clear if allocated
	strmem = new char[strlen(input)+1];
	int i = 0;
	do {
		if(input[i] >= 'a' && input[i] <= 'z') {
			strmem[i] = input[i] - 'a' + 'A';
		}
		else {
			strmem[i] = input[i];
		}
		i++;
	} while(input[i] != '\0');
	strmem[i] = '\0';
	return strmem;
}

char* cutBorders(char* input, int left = 1, int right = 1) {
    delete strmem;  ///clear if allocated
    int len = strlen(input);
    strmem = new char[len-left-right+1];
    for(int i = 0; i < len-left-right; i++) {
        strmem[i] = input[i+left];
    }
	strmem[len-left-right] = '\0';
    return strmem;
}

char* stringProcess(char* input) {
    delete strmem;
    strmem = new char[strlen(input)+1];
    int src = 0, mem = 0;
    do {
        if(input[src] != '\\') {
            strmem[mem] = input[src];
            src++;
            mem++;
        }
        else if(input[src] == '\\') {
            switch(input[src+1]) {
            case '\n':
                src += 2;
                break;
            case 'n':
                strmem[mem] = '\n';
                src += 2;
                mem++;
                break;
            case 't':
                strmem[mem] = '\t';
                src += 2;
                mem++;
                break;
            case '\'':
                strmem[mem] = '\'';
                src += 2;
                mem++;
                break;
            case '\\':
                strmem[mem] = '\\';
                src += 2;
                mem++;
                break;
            case '\"':
                strmem[mem] = '\"';
                src += 2;
                mem++;
                break;
            case 'a':
                strmem[mem] = '\a';
                src += 2;
                mem++;
                break;
            case 'f':
                strmem[mem] = '\f';
                src += 2;
                mem++;
                break;
            case 'r':
                strmem[mem] = '\r';
                src += 2;
                mem++;
                break;
            case 'b':
                strmem[mem] = '\b';
                src += 2;
                mem++;
                break;
            case 'v':
                strmem[mem] = '\v';
                src += 2;
                mem++;
                break;
            case '0':
                strmem[mem] = '\0';
                src += 2;
                mem++;
                break;
            default:
                strmem[mem] = input[src+1];
                src += 2;
                mem++;
            }
        }
    } while(input[src] != '\0');
	strmem[mem] = '\0';
    return strmem;
}

void updateLineCount(char* input) {
    int src = 0;
    do {
        if(input[src] == '\n')
            line_count++;
        src++;
    } while(input[src] != '\0');
}

#line 651 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 150 "scannerwork.l"


#line 805 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 172 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 340 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 152 "scannerwork.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 154 "scannerwork.l"
{line_count++;}
	YY_BREAK
case 3:
#line 157 "scannerwork.l"
case 4:
#line 158 "scannerwork.l"
case 5:
#line 159 "scannerwork.l"
case 6:
#line 160 "scannerwork.l"
case 7:
#line 161 "scannerwork.l"
case 8:
#line 162 "scannerwork.l"
case 9:
#line 163 "scannerwork.l"
case 10:
#line 164 "scannerwork.l"
case 11:
#line 165 "scannerwork.l"
case 12:
#line 166 "scannerwork.l"
case 13:
#line 167 "scannerwork.l"
case 14:
#line 168 "scannerwork.l"
case 15:
#line 169 "scannerwork.l"
case 16:
#line 170 "scannerwork.l"
case 17:
#line 171 "scannerwork.l"
case 18:
YY_RULE_SETUP
#line 171 "scannerwork.l"
{
		fprintf(tokenout, "<%s> ", toUppercase(yytext));
		fprintf(logout,"Line No. %d: Token <%s> Lexeme %s found\n\n", line_count, toUppercase(yytext), yytext);
	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 176 "scannerwork.l"
{
		int i = 3;
		fprintf(tokenout,"<CONST_INT,%s> ",yytext);
		fprintf(logout,"Line No. %d: Token <CONST_INT> Lexeme %s found\n\n",line_count,yytext);

		//insert in symbol table and print symbol table content(only non empty buckets)
		if(table.insert(yytext,"ID")) {
			table.printCurrentScopeTable(logout);
		}
	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 187 "scannerwork.l"
{

		fprintf(tokenout,"<CONST_FLOAT,%s> ",yytext);
		fprintf(logout,"Line No. %d: Token <CONST_FLOAT> Lexeme %s found\n\n",line_count,yytext);

		//insert in symbol table and print symbol table content(only non empty buckets)
		if(table.insert(yytext,"ID")) {
			table.printCurrentScopeTable(logout);
		}
	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 198 "scannerwork.l"
{
			fprintf(tokenout,"<CONST_CHAR,%s> ",cutBorders(yytext));
			fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_count,yytext);

			//insert in symbol table and print symbol table content(only non empty buckets)
			if(table.insert(yytext,"ID")) {
				table.printCurrentScopeTable(logout);
			}
		}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 209 "scannerwork.l"
{
					fprintf(tokenout,"<CONST_CHAR,%s> ",cutBorders(yytext,2));
					fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_count,yytext);

					//insert in symbol table and print symbol table content(only non empty buckets)
					if(table.insert(yytext,"ID")) {
						table.printCurrentScopeTable(logout);
					}
				}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 219 "scannerwork.l"
{
			fprintf(tokenout,"<CONST_CHAR,\n> ");
			fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_count,yytext);

			//insert in symbol table and print symbol table content(only non empty buckets)
			if(table.insert(yytext,"ID")) {
				table.printCurrentScopeTable(logout);
			}
		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 229 "scannerwork.l"
{
	fprintf(tokenout,"<CONST_CHAR,\t> ");
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_count,yytext);

	//insert in symbol table and print symbol table content(only non empty buckets)
	if(table.insert(yytext,"ID")) {
		table.printCurrentScopeTable(logout);
	}
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 239 "scannerwork.l"
{
	fprintf(tokenout,"<CONST_CHAR,\a> ");
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_count,yytext);

	//insert in symbol table and print symbol table content(only non empty buckets)
	if(table.insert(yytext,"ID")) {
		table.printCurrentScopeTable(logout);
	}
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 249 "scannerwork.l"
{
	fprintf(tokenout,"<CONST_CHAR,\f> ");
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_count,yytext);

	//insert in symbol table and print symbol table content(only non empty buckets)
	if(table.insert(yytext,"ID")) {
		table.printCurrentScopeTable(logout);
	}
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 259 "scannerwork.l"
{
	fprintf(tokenout,"<CONST_CHAR,\r> ");
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_count,yytext);

	//insert in symbol table and print symbol table content(only non empty buckets)
	if(table.insert(yytext,"ID")) {
		table.printCurrentScopeTable(logout);
	}
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 269 "scannerwork.l"
{
	fprintf(tokenout,"<CONST_CHAR,\b> ");
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_count,yytext);

	//insert in symbol table and print symbol table content(only non empty buckets)
	if(table.insert(yytext,"ID")) {
		table.printCurrentScopeTable(logout);
	}
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 279 "scannerwork.l"
{
	fprintf(tokenout,"<CONST_CHAR,\v> ");
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_count,yytext);

	//insert in symbol table and print symbol table content(only non empty buckets)
	if(table.insert(yytext,"ID")) {
		table.printCurrentScopeTable(logout);
	}
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 289 "scannerwork.l"
{
	fprintf(tokenout,"<CONST_CHAR,\0> ");
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_count,yytext);

	//insert in symbol table and print symbol table content(only non empty buckets)
	if(table.insert(yytext,"ID")) {
		table.printCurrentScopeTable(logout);
	}
}
	YY_BREAK
case 31:
#line 300 "scannerwork.l"
case 32:
YY_RULE_SETUP
#line 301 "scannerwork.l"
{
			fprintf(tokenout,"<ADDOP,%s> ",yytext);
			fprintf(logout,"Line No. %d: Token <ADDOP> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 33:
#line 307 "scannerwork.l"
case 34:
#line 308 "scannerwork.l"
case 35:
YY_RULE_SETUP
#line 308 "scannerwork.l"
{
			fprintf(tokenout,"<MULOP,%s> ",yytext);
			fprintf(logout,"Line No. %d: Token <MULOP> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 36:
#line 314 "scannerwork.l"
case 37:
YY_RULE_SETUP
#line 314 "scannerwork.l"
{
			fprintf(tokenout,"<INCOP,%s> ",yytext);
			fprintf(logout,"Line No. %d: Token <INCOP> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 38:
#line 320 "scannerwork.l"
case 39:
#line 321 "scannerwork.l"
case 40:
#line 322 "scannerwork.l"
case 41:
#line 323 "scannerwork.l"
case 42:
#line 324 "scannerwork.l"
case 43:
YY_RULE_SETUP
#line 324 "scannerwork.l"
{
			fprintf(tokenout,"<RELOP,%s> ",yytext);
			fprintf(logout,"Line No. %d: Token <RELOP> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 329 "scannerwork.l"
{
	fprintf(tokenout,"<ASSIGNOP,%s> ",yytext);
	fprintf(logout,"Line No. %d: Token <ASSIGNOP> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 45:
#line 335 "scannerwork.l"
case 46:
YY_RULE_SETUP
#line 335 "scannerwork.l"
{
			fprintf(tokenout,"<LOGICOP,%s> ",yytext);
			fprintf(logout,"Line No. %d: Token <LOGICOP> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 47:
#line 340 "scannerwork.l"
case 48:
#line 341 "scannerwork.l"
case 49:
#line 342 "scannerwork.l"
case 50:
#line 343 "scannerwork.l"
case 51:
YY_RULE_SETUP
#line 343 "scannerwork.l"
{
			fprintf(tokenout,"<BITOP,%s> ",yytext);
			fprintf(logout,"Line No. %d: Token <BITOP> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 348 "scannerwork.l"
{
		fprintf(tokenout,"<NOT,%s> ",yytext);
		fprintf(logout,"Line No. %d: Token <NOT> Lexeme %s found\n\n",line_count,yytext);
	}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 354 "scannerwork.l"
{
		fprintf(tokenout,"<LPAREN,%s> ",yytext);
		fprintf(logout,"Line No. %d: Token <LPAREN> Lexeme %s found\n\n",line_count,yytext);
	}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 359 "scannerwork.l"
{
		fprintf(tokenout,"<RPAREN,%s> ",yytext);
		fprintf(logout,"Line No. %d: Token <RPAREN> Lexeme %s found\n\n",line_count,yytext);
	}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 364 "scannerwork.l"
{
		fprintf(tokenout,"<LCURL,%s> ",yytext);
		fprintf(logout,"Line No. %d: Token <LCURL> Lexeme %s found\n\n",line_count,yytext);
	}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 369 "scannerwork.l"
{
		fprintf(tokenout,"<RCURL,%s> ",yytext);
		fprintf(logout,"Line No. %d: Token <RCURL> Lexeme %s found\n\n",line_count,yytext);
	}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 374 "scannerwork.l"
{
		fprintf(tokenout,"<LTHIRD,%s> ",yytext);
		fprintf(logout,"Line No. %d: Token <LTHIRD> Lexeme %s found\n\n",line_count,yytext);
	}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 379 "scannerwork.l"
{
		fprintf(tokenout,"<RTHIRD,%s> ",yytext);
		fprintf(logout,"Line No. %d: Token <RTHIRD> Lexeme %s found\n\n",line_count,yytext);
	}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 384 "scannerwork.l"
{
		fprintf(tokenout,"<COMMA,%s> ",yytext);
		fprintf(logout,"Line No. %d: Token <COMMA> Lexeme %s found\n\n",line_count,yytext);
	}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 389 "scannerwork.l"
{
		fprintf(tokenout,"<SEMICOLON,%s> ",yytext);
		fprintf(logout,"Line No. %d: Token <SEMICOLON> Lexeme %s found\n\n",line_count,yytext);
	}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 394 "scannerwork.l"
{

		fprintf(tokenout,"<ID,%s> ",yytext);
		fprintf(logout,"Line No. %d: Token <ID> Lexeme %s found\n\n",line_count,yytext);

		//insert in symbol table and print symbol table content(only non empty buckets)
		if(table.insert(yytext,"ID")) {
			table.printCurrentScopeTable(logout);
		}
	}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 405 "scannerwork.l"
{

		fprintf(tokenout,"<STRING,%s> ",stringProcess(yytext));
		fprintf(logout,"Line No. %d: Token <STRING> Lexeme %s found\n\n",line_count,yytext);
		updateLineCount(yytext);
	}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 412 "scannerwork.l"
{

	fprintf(logout,"Line No. %d: Token <COMMENT> Lexeme %s found\n\n", line_count,yytext);
	updateLineCount(yytext);
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 418 "scannerwork.l"
{
	fprintf(logout,"Line No. %d: Token <COMMENT> Lexeme %s found\n\n", line_count,yytext);
	updateLineCount(yytext);
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 423 "scannerwork.l"
{
	fprintf(logout,"Error at line %d: Too many decimal point %s\n\n",line_count,yytext);
	error_count++;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 428 "scannerwork.l"
{
	fprintf(logout,"Error at line %d: Ill formed number %s\n\n",line_count,yytext);
	error_count++;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 433 "scannerwork.l"
{
	fprintf(logout,"Error at line %d: Invalid prefix on ID or invalid suffix on Number %s\n\n",line_count,yytext);
	error_count++;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 438 "scannerwork.l"
{
	fprintf(logout,"Error at line %d: Empty character constant error_count %s\n\n",line_count,yytext);
	error_count++;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 443 "scannerwork.l"
{
	fprintf(logout,"Error at line %d: Unterminated character %s\n\n",line_count,yytext);
	error_count++;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 448 "scannerwork.l"
{
	fprintf(logout,"Error at line %d: Multi character constant error_count %s\n\n",line_count,yytext);
	error_count++;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 453 "scannerwork.l"
{

		fprintf(logout,"Error at line %d: Unterminated String %s\n\n",line_count,yytext);
		updateLineCount(yytext);
		error_count++;
	}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 460 "scannerwork.l"
{
	fprintf(logout,"Error at line %d: Unterminated comment %s\n\n",line_count,yytext);
	updateLineCount(yytext);
	error_count++;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 466 "scannerwork.l"
{
	fprintf(logout,"Error at line %d: Unrecognized character %s",line_count,yytext);
	error_count++;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 471 "scannerwork.l"
ECHO;
	YY_BREAK
#line 1371 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 172 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 172 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 171);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 471 "scannerwork.l"


int main(int argc,char *argv[]){

	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}

	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}

	logout= fopen("log.txt","w");
	tokenout= fopen("token.txt","w");

	yyin = fin;
	yylex();
	
	fprintf(logout,"Total lines: %d\n",line_count);
	fprintf(logout,"Total error_counts: %d\n",error_count);
	
	fclose(yyin);
	fclose(tokenout);
	fclose(logout);
	return 0;
}
